apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "app-demo"
  description: "app-demo"
  annotations:
    github.com/project-slug: veecode-platform-mr/app-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/demo"
